### ISSUE TITLE
Fighting with env var configs using the AWS cli

### ISSUE THREAD

**Issue by Jeffail** [benthosdev/benthos-lambda#2]
I'm trying to document a sane way of doing env var based configuration for this and I'm currently at my wits end. I've got this so far:

``` sh
BENTHOS_CONFIG=`cat ./yourconfig.yaml`
aws lambda create-function \
  --runtime go1.x \
  --handler benthos-lambda \
  --role benthos-example-role \
  --zip-file fileb://benthos-lambda.zip \
  --environment "TODO: This syntax is a nightmare" \
  --function-name benthos-example
```

I've tried many combinations of both the `Variables={KeyName1=string,KeyName2=string}` and `{"Variables": {"KeyName1": "string"}}` syntaxes and so far every method of trying to inject a YAML or JSON config is utterly gross.

**Comment by Jeffail** [comment]
Any ideas @asiragusa  @kconwayatlassian? Is this something that's already solved somewhere?

**Comment by Jeffail** [comment]
jq to the rescue, got this working:

``` sh
LAMBDA_ENV=`cat yourconfig.yaml | jq -csR {Variables:{BENTHOS_CONFIG:.}}`
aws lambda create-function \
  --runtime go1.x \
  --handler benthos-lambda \
  --role benthos-example-role \
  --zip-file fileb://benthos-lambda.zip \
  --environment "$LAMBDA_ENV" \
  --function-name benthos-example
```

It ain't the most graceful, but it works for now. If anyone has a more elegant solution let me know.

**Comment by asiragusa** [comment]
Sorry for being late, I have just seen your message.

Your scripts looks quite neat to me, you can change it to be a one-liner (if you want) by doing the following:
```bash
aws lambda create-function \
  --runtime go1.x \
  --handler benthos-lambda \
  --role benthos-example-role \
  --zip-file fileb://benthos-lambda.zip \
  --environment "`cat yourconfig.yaml | jq -csR {Variables:{BENTHOS_CONFIG:.}}`" \
  --function-name benthos-example
```

In my experience it's way faster to first upload the zip file to a s3 bucket. Consider using also `aws lambda update-function-code` and `aws lambda update-function-configuration`

I deploy the lambda in production using Terraform: 

```hcl
resource "aws_lambda_function" "benthos" {
  function_name = "benthos"
  role          = "${aws_iam_role.lambda-role.arn}"
  handler       = "build/benthos"
  runtime       = "go1.x"

  s3_bucket = "${var.bucket_name}"
  s3_key    = "benthos-${var.version}.zip"

  environment {
    variables = {
      LAMBDA_ENV = "${data.template_file.conf.rendered}"
    }
  }
}
```

We might provide a terraform module with the repository to simplify the deployment, I can help with if you want.

For local testing I managed to use AWS sam, it's the fastest way to test your lambda:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Testbed for lambda benthos input'
Resources:
  dynamodbstreams:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: build/benthos
      Runtime: go1.x
      Description: 'Testbed for lambda benthos input'
      MemorySize: 256
      Timeout: 5
      Environment:
        Variables:
          YAML_CONFIG: |
            logger:
              prefix: benthos
              level: TRACE
              add_timestamp: true
              json_format: true
              static_fields:
                '@service': benthos

            input:
              type: lambda
              plugin: {}

            pipeline:
              processors:
                - type: filter_parts
                  filter_parts:
                    type: metadata
                    metadata:
                      operator: equals
                      part: 0
                      key: dynamodbstreams_event_name
                      arg: INSERT

            output:
              type: stdout

```

and I invoke `sam` using the following script:
```bash
#!/usr/bin/env bash

set -e

PAYLOAD=$1

if [[ -z "$PAYLOAD" ]]; then
    echo "You must provide a payload file"
    exit 1
fi

GOOS=linux GOARCH=amd64 go build -o build/benthos .

sam local invoke dynamodbstreams -t template.yaml -e $1
```

the first argument is a file containing the JSON input. 

Btw the build part can be skipped and the script easily adapted to take the payload and the config file as inputs.

Hope it helps :)
